<a href="https://colab.research.google.com/github/uob-positron-imaging-centre/PEPT-Algorithms-RoPP/blob/main/GMeans_RoPP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank"  href="https://github.com/uob-positron-imaging-centre/pept"><img src="https://github.com/uob-positron-imaging-centre/misc-hosting/blob/master/logo.png?raw=true" style="height:200px; display: block; margin-left: auto; margin-right: auto;"/></a>

# Interactive PEPT Analysis Examples using *the G-Means algorithm*

> [1] Wiggins C, Santos R, Ruggles A. A novel clustering approach to positron emission particle tracking. Nuclear Instruments and Methods in Physics Research Section A: Accelerators, Spectrometers, Detectors and Associated Equipment. 2016 Mar 1;811:18-24.

---

#### Copyright 2021 the `pept` developers
##### Jupyter Notebook authored by Andrei Leonard Nicusan and Dr. Kit Windows-Yule for the "PEPT: A Comparative Review" paper, commissioned by the Reports on Progress in Physics journal

Licensed under the GNU License, Version 3.0 (the "License").

---


# 1. Introduction

Positron emission particle tracking (PEPT) is a powerful technique allowing the non-invasive, three-dimensional tracking of one or more radioactive 'tracer' particles through particulate, fluid or multiphase systems. It allows particle or fluid motion to be tracked with sub-millimetre accuracy and sub-millisecond temporal resolution and, due to its use of highly-penetrating 511keV gamma rays, can be used to probe the internal dynamics of even large, dense, optically opaque systems <sup>[[2]](https://www.sciencedirect.com/science/article/pii/016890029390864E) [[3]](https://www.sciencedirect.com/science/article/pii/S0263876208003341) [[4]](https://aip.scitation.org/doi/abs/10.1063/1.4983046@rsi.2017.IMGP2017.issue-1)</sup>. In light of its versatility both in terms of the scales and materials of particles which can be tracked <sup>[[5]](https://www.sciencedirect.com/science/article/pii/S1672251507001455)[[6]](https://www.sciencedirect.com/science/article/pii/S0168900206005341)</sup>, and the sizes and geometries of the systems which can be imaged <sup>[[7]](https://www.sciencedirect.com/science/article/pii/S0168900209001880) [[8]](https://www.sciencedirect.com/science/article/pii/S0029549316000273)</sup> , the technique has wide-ranging applicability in diverse scientific, industrial and biomedical applications.

PEPT is performed by radioactively labelling a particle with a positron-emitting radioisotope such as Fluorine-18 ($^{18}\mathrm{F}$) or Gallium-68 ($^{68}\mathrm{Ga}$), and using the back-to-back gamma rays produced by electron-positron annihilation events in and around the tracer to triangulate its spatial position. Each detected gamma ray represents a **line of response (LoR)** .

## 1.1. This Jupyter Notebook

This interactive Jupyter Notebook illustrates the main processing steps employed by the G-Means algorithm<sup>[1]</sup> for radioactive tracer tracking, as described in the Reports on Progress in Physics "PEPT: A Comparative Review" paper.

An [example dataset](https://raw.githubusercontent.com/uob-positron-imaging-centre/example_data/master/sample_1p_fluidised_bed.csv) is used from an experiment run at the University of Birmingham Positron Imaging Centre using the ADAC Forté by Matthew Herald. It consists of a single 1 mm diameter MCC particle activated with Fluorine-18 radioactive tracer material inside a bubbling fluidised bed. The fluidised bed was filled with 90% sand and 10% MCC; air was fed into the bottom of the bed at a rate of 37 litres per minute at 3.5 bar. This dataset was chosen for its high quality captured lines of response, with the tracer still depicting the random particle motion that is inherent to bubbling fluidised beds - and typical in Lagrangian particle tracking.

The [`pept`](https://github.com/uob-positron-imaging-centre/pept) Python library is used for initialising and visualising PEPT data. While not required *per se* for illustrating PEPT algorithms' processing steps, it significantly reduces the amount of repetitive code and visual noise, allowing the reader to focus on the main conceptual procedures.

## 1.2. Running Code Cells
Select any code cell and click on the (▶) sign in the top-left of the cell's frame to run its code (note that code cells have to be run in order when running for the first time).

In [1]:
# First install the `pept` library using pip, Python's package manager
!pip install pept

# 2. The G-Means Algorithm

Next, we need to install the necessary libraries to be able to use the (general) G-means clustering algorithm itself.

In [2]:
# Install the `pyclustering` library to have access to G-Means
!pip install pyclustering

## 2.1. Read in Line of Response Data
In this initial step, we read in the "raw" LoR data from which our tracer positions are calculated. In this simple example, we load only a single sample (i.e. one particle location at one point in time). The LoRs corresponding to this sample are output as an image.

As discussed in the main text, varying the numbers of LoRs used to calculate a PEPT location can affect the quality of the final location measured. Try altering the value "nrows" below to see how this inluences your results.

In [3]:
# Read in a sample of experimental PEPT data from an online repository into a NumPy array
import numpy as np
import pept

# Skip the file header's first 15 lines, then read in 50 LoRs
lors_raw = pept.utilities.read_csv(
    "https://raw.githubusercontent.com/uob-positron-imaging-centre/example_data/master/sample_1p_fluidised_bed.csv",
    skiprows = 15,
    nrows = 50,
)

# Insert columns for the z-coordinates
head_separation = 600

lors_raw = np.insert(lors_raw, 3, 0, axis = 1)
lors_raw = np.insert(lors_raw, 6, head_separation, axis = 1)

# Project the 3D lines onto the YZ plane for ease of analysis - i.e. select only columns
# [time, y1, z1, y2, z2] and flip columns to get [time, x1, y1, x2, y2]
lors = np.array(lors_raw[:, [0, 3, 2, 6, 5]])

# Print the line of response (LoR) data
lors

array([[0.000e+00, 0.000e+00, 1.687e+02, 6.000e+02, 1.428e+02],
       [1.000e-01, 0.000e+00, 1.676e+02, 6.000e+02, 3.139e+02],
       [1.000e-01, 0.000e+00, 4.100e+02, 6.000e+02, 2.401e+02],
       [2.000e-01, 0.000e+00, 2.962e+02, 6.000e+02, 4.525e+02],
       [2.000e-01, 0.000e+00, 1.151e+02, 6.000e+02, 3.534e+02],
       [2.000e-01, 0.000e+00, 1.322e+02, 6.000e+02, 2.661e+02],
       [2.000e-01, 0.000e+00, 3.735e+02, 6.000e+02, 1.310e+02],
       [3.000e-01, 0.000e+00, 1.115e+02, 6.000e+02, 3.534e+02],
       [4.000e-01, 0.000e+00, 2.094e+02, 6.000e+02, 2.808e+02],
       [4.000e-01, 0.000e+00, 2.749e+02, 6.000e+02, 3.062e+02],
       [5.000e-01, 0.000e+00, 2.389e+02, 6.000e+02, 1.681e+02],
       [6.000e-01, 0.000e+00, 4.283e+02, 6.000e+02, 7.020e+01],
       [6.000e-01, 0.000e+00, 1.333e+02, 6.000e+02, 3.499e+02],
       [6.000e-01, 0.000e+00, 3.050e+02, 6.000e+02, 1.032e+02],
       [6.000e-01, 0.000e+00, 9.200e+01, 6.000e+02, 3.929e+02],
       [6.000e-01, 0.000e+00, 1.859e+02,

In [4]:
from pept.visualisation import PlotlyGrapher2D

grapher = PlotlyGrapher2D()
grapher.add_lines(lors)
grapher.show()

## 2.2. Voxelise / Pixelise the Lines of Response
The next step is to 'voxelise' the LoRs - that is, to create a grid of square or rectangular cells, and count the number of lines passing through each. For simplicity and ease of visualisation, we work here in 2D, but the real algorithm of course works in 3D.

In the code below you can set the resolution - i.e. pixel size - by varying the pair of values corresponding to the `resolution` parameter. Typing, for example, (20,20) will give a 20 by 20 grid of pixels.

Try some different values for the `resolution` parameter. As discussed in the main text, larger values - i.e. a higher resolution, smaller pixels - will allow the centroid of our particle to be determined more precisely. However, you may notice that as you increase these values your processor may take longer in the calculation and plotting steps below. Now imagine this is just one of many thousands of locations, and you may get an idea of the issue of using an overly-fine grid. As discussed in the main text, when using codes relying on voxelisation, there is a fine balance to be made between precision and compuationaly efficiency.

In [5]:
resolution = (20, 20)
pixels = pept.Pixels.from_lines(lors, resolution)

pixels

Initialised Pixels class in 0.0004870891571044922 s.


Class instance that inherits from `pept.Pixels`.
Type:
<class 'pept.base.pixel_data.Pixels'>

Attributes
----------
[[ 0.  2.  3.  7.  7.  7.  5.  4.  2. 10.  5.  2.  3.  6.  5.  0.  0.  0.
   0.  0.]
 [ 0.  0.  2.  3.  8.  8.  7.  4.  4.  9.  3.  2.  3.  6.  2.  0.  0.  0.
   0.  0.]
 [ 0.  0.  2.  4.  8. 10.  7.  3.  5.  8.  3.  2.  8.  6.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  3.  4. 14.  8.  4.  7.  8.  5.  3.  7.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  2.  3. 13. 11.  6.  7.  6.  5.  8.  6.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  3.  8. 13.  8.  9.  7.  7.  8.  1.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  2.  5. 11. 13. 10.  6.  8.  5.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  1.  5. 10. 18. 10. 10.  7.  3.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  1.  2.  6. 19. 14. 10.  4.  4.  1.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  2.  2.  5. 19. 23.  8.  3.  2.  1.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  2.  2.  4. 18. 

In [6]:
grapher = PlotlyGrapher2D()

grapher.add_pixels(pixels)
grapher.add_lines(lors, color = "red")

grapher.show()

## 2.3. High Pass Filter

As is clear from the above image, our data possesses a lot of background noise away from where we would expect the tracer's centre to be. The G-means PEPT algorithm takes a relatively straightforward approach to removing this noise, simply setting a threshold pixel value (i.e. line density) below which all data are removed. Specifically, a `fraction` of the maximum pixel value for a given sample of LoRs is chosen.

Try varying the `fraction` parameter below to see how this choice affects your data.

In [7]:
# Set all pixel values smaller than a `fraction` of the maximum `pixels` value to zero
fraction = 0.4
threshold = fraction * float(pixels.max())

pixels[pixels < threshold] = 0.

In [8]:
grapher = PlotlyGrapher2D()
grapher.add_pixels(pixels)
grapher.show()

## 2.4. Cluster Voxels / Pixels with G-Means 

In this step, the "G-Means" implementation from the `pyclustering` Python library is used.

To cluster the pixels, they must first be written as a data table, such that the columns are the data features (here a pixel centre's Euclidean position) and the rows are the data samples (here the non-zero pixels). To add more weight to pixels with larger values, each data sample is repeated by the number of LoRs passing through.

In [9]:
# Write non-zero pixels as a data table, where the feature columns are the XY pixel positions.
origin = np.array([pixels.xlim[0], pixels.ylim[0]])

samples_table = []
for i in range(pixels.shape[0]):
    for j in range(pixels.shape[1]):
        # Repeat the number of data points in the `samples_table` by the individual pixel's value
        for k in range(int(pixels[i, j])):
            position = origin + pixels.pixel_size * ([i, j]) + pixels.pixel_size * 0.5
            samples_table.append(position)

samples_table = np.array(samples_table)
samples_table

array([[105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [105., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [135., 165.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [165., 195.],
       [195., 225.],
       [195., 225.],
       [195., 225.],
       [195., 225.],
       [195., 225.],
       [195., 225.],
       [195., 225.],
       [195.,

### 2.4.1 Merging cluster centres

By default, with data presented in the manner used for this PEPT algorithm, the G-means algorithm will return a cluster _in every voxel_!

As such, an extra step must be added to merge the centres of clusters. Specifically, any centres less than 2 pixels apart are merged into a single cluster.

In [10]:
# Run G-Means to cluster data into Gaussian partitions
from pyclustering.cluster.gmeans import gmeans
from scipy.cluster.hierarchy import linkage, fcluster

gmeans_instance = gmeans(samples_table, repeat = 20).process()

# Extract clustering results: clusters and their centers
clusters = gmeans_instance.get_clusters()
centres = gmeans_instance.get_centers()
centres = np.array([np.array(c) for c in centres])

# Merge centres that are less than 2 pixel sizes apart
max_distance = 2 * np.linalg.norm(pixels.pixel_size)
centres_merged_labels = fcluster(linkage(centres), t = max_distance, criterion='distance')

centres_merged = []
for label in range(1, centres_merged_labels.max() + 1):
    centre = centres[centres_merged_labels == label].mean(axis = 0)
    centres_merged.append(centre)

centres_merged = np.array(centres_merged)

# Insert the tracer positions' timestamp at column 0
centres_merged = np.insert(centres_merged, 0, lors[:, 0].mean(), axis = 1)
samples_time = np.insert(samples_table, 0, lors[:, 0].mean(), axis = 1)

centres_merged

array([[  0.938     , 299.21052632, 236.05263158]])

In [11]:
grapher = PlotlyGrapher2D()

grapher.add_pixels(pixels)
for cluster_indices in clusters:
    grapher.add_points(samples_time[cluster_indices])

grapher.add_points(centres_merged, color = "red", size = 15)

grapher.show()

# 3. Complete G-Means Code

In [12]:
# Read in a sample of experimental PEPT data from an online repository into a NumPy array
import numpy as np
import pept

# Skip the file header's first 15 lines, then read in 50 LoRs
lors_raw = pept.utilities.read_csv(
    "https://raw.githubusercontent.com/uob-positron-imaging-centre/example_data/master/sample_1p_fluidised_bed.csv",
    skiprows = 15,
    nrows = 80_000,
)

# Insert columns for the z-coordinates
head_separation = 600

lors_raw = np.insert(lors_raw, 3, 0, axis = 1)
lors_raw = np.insert(lors_raw, 6, head_separation, axis = 1)

# Project the 3D lines onto the YZ plane for ease of analysis - i.e. select only columns
# [time, y1, z1, y2, z2] and flip columns to get [time, x1, y1, x2, y2]
lors = np.array(lors_raw[:, [0, 3, 2, 6, 5]])

# Print the line of response (LoR) data
lors

array([[0.0000e+00, 0.0000e+00, 1.6870e+02, 6.0000e+02, 1.4280e+02],
       [1.0000e-01, 0.0000e+00, 1.6760e+02, 6.0000e+02, 3.1390e+02],
       [1.0000e-01, 0.0000e+00, 4.1000e+02, 6.0000e+02, 2.4010e+02],
       ...,
       [2.6443e+03, 0.0000e+00, 2.2480e+02, 6.0000e+02, 3.4280e+02],
       [2.6444e+03, 0.0000e+00, 1.3690e+02, 6.0000e+02, 1.4750e+02],
       [2.6444e+03, 0.0000e+00, 5.4220e+02, 6.0000e+02, 5.5280e+02]])

In [13]:
# Use the G-Means algorithm to track moving tracer
from pyclustering.cluster.gmeans import gmeans
from scipy.cluster.hierarchy import linkage, fcluster

# User-definable G-Means settings
fraction = 0.5              # Set all pixels lower than `fraction` of maximum pixel value to zero
resolution = (100, 100)     # Number of pixels in each dimension
sample_size = 100           # Number of LoRs in a sample

sample_start = 0
positions = []

while sample_start + sample_size < len(lors):
    sample = lors[sample_start:sample_start + sample_size]

    # Pixellise sample of LoRs
    pixels = pept.Pixels.from_lines(sample, resolution, verbose = False)

    # Set all pixel values smaller than a `fraction` of the maximum `pixels` value to zero
    threshold = fraction * float(pixels.max())
    pixels[pixels < threshold] = 0.

    # Write non-zero pixels as a data table, where the feature columns are the XY pixel positions.
    origin = np.array([pixels.xlim[0], pixels.ylim[0]])

    samples_table = []
    for i in range(pixels.shape[0]):
        for j in range(pixels.shape[1]):
            # Repeat the number of data points in the `samples_table` by the pixel's value
            for k in range(int(pixels[i, j])):
                position = origin + pixels.pixel_size * ([i, j]) + pixels.pixel_size * 0.5
                samples_table.append(position)

    samples_table = np.array(samples_table)

    # Run G-Means to cluster data into Gaussian partitions
    gmeans_instance = gmeans(samples_table, repeat = 10).process()

    # Extract clustering results: clusters and their centers
    clusters = gmeans_instance.get_clusters()
    centres = gmeans_instance.get_centers()
    centres = np.array([np.array(c) for c in centres])

    # Merge centres that are less than 2 pixel sizes apart
    max_distance = 2 * np.linalg.norm(pixels.pixel_size)
    centres_merged_labels = fcluster(linkage(centres), t = max_distance, criterion='distance')

    centres_merged = []
    for label in range(1, centres_merged_labels.max() + 1):
        centre = centres[centres_merged_labels == label].mean(axis = 0)
        centres_merged.append(centre)

    centres_merged = np.array(centres_merged)

    # Insert the tracer positions' timestamp at column 0
    centres_merged = np.insert(centres_merged, 0, sample[:, 0].mean(), axis = 1)
    samples_time = np.insert(samples_table, 0, sample[:, 0].mean(), axis = 1)

    # Collect potitions found
    positions.extend(centres_merged)

    sample_start += sample_size

positions = np.array(positions)
positions

array([[1.93100000e+00, 3.21545455e+02, 2.46272727e+02],
       [5.87800000e+00, 3.10000000e+02, 2.47333333e+02],
       [9.96600000e+00, 3.18000000e+02, 2.43000000e+02],
       ...,
       [2.63312800e+03, 3.05117647e+02, 2.94176471e+02],
       [2.63674900e+03, 3.06000000e+02, 2.94000000e+02],
       [2.63997100e+03, 3.07666667e+02, 2.93666667e+02]])

In [14]:
from pept.visualisation import PlotlyGrapher2D

grapher = PlotlyGrapher2D(
    cols = 3,
    subplot_titles = ["First 400 LoRs", "High Pass Filtered Pixels", "Positions Found"],
)

grapher.add_lines(lors[:400])
grapher.add_pixels(pixels, col = 2)
grapher.add_points(positions, col = 3)

grapher.show()